### PR TITLE
Remove binary __slots__ values

### PR DESCRIPTION
**Pull request by jayvdb**
They are not Python 3 compatible

### CODE REVIEW

**Comment by jayvdb** [comment]
fwiw, I have a Python 3 branch which still has a lot of failures during `py.test`, but isnt too far away from being usable, if only to prevent further regressions.

**Comment by jayvdb** [comment]
hmm. seem travis isnt providing builds for PRs.
Here is my travis build of this commit: https://travis-ci.org/jayvdb/spreads/builds/120844859

**Comment by jbaiter** [comment]
I vaguely remember there being a reason for those explicit bytestrings (to override, but I honestly cannot remember any more :/ But the tests are all passing, so we should be good :-)
Weird about Travis, I'll have to check the configuration, thank you for pointing that out.

However, which Python 3 version are you targeting with your branch? Starting with Python 3.4 the bytestring literal syntax is supported again.

Thank you for your work, Python 3 compatibility has been on my radar for a while, glad to see someone taking the initiative on it :-) If you notice some of my other packages that spreads depends on (`chdkptp.py`, `gphoto2-cffi`, `jpegtran-cffi`, etc) having trouble with Python3, please open an issue on the relevant project and I'll take care of it.

**Comment by jayvdb** [comment]
Im targetting 3.4+ initially.

Good to know you're keen, and willing to merge preliminary patches.

Will push a working .travis.yml with 3.4 in the matrix asap, so it is on everyones radar.

**Comment by jbaiter** [comment]
If it's not too much hassle for you, I'd prefer it if you collected all Py3-related changes in a single pull request that I can review from time to time and then merge once all the tests are passing on Python 2.7 and Python 3.4.

**Comment by jayvdb** [comment]
I'd prefer to get a few of the basic underlying build problems fixed with early PRs.  e.g. this one and #224 , where you'll know better than I can if the basic fix is probably ok, but real world testing is also going to be needed.

As for the actual code changes, I'll do a clean series, and you can identify any that you'd like me to submit as PRs early, if any.

**Pull request merged**
